version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
    restart: on-failure

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    restart: on-failure
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=access_log
    ports:
      - "3306:3306"
    volumes:
      - logs:/var/log/mysql
      - data:/var/lib/mysql

volumes:
  data:
  logs:
