name: Push to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 930354804502
  ECR_REPO: whist-exam-app
  IMAGE_NAME: app

jobs:
  push_to_ecr:
    name: Push to ECR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: configure aws cred
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Extract branch name
      shell: bash
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      id: branch_name

    - name: Extract sha in a short form
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      id: sha_short
      
    - name: Build and push image to ECR
      id: build-and-push
      env:
          ECR_REPOSITORY: whist-exam-app
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          FULL_IMAGE: ${{ steps.branch_name.outputs.branch }}-${{ steps.sha_short.outputs.sha_short}}
      run: |
       docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
       docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$ECR_REPOSITORY-$FULL_IMAGE .
       docker push $ECR_REGISTRY/$ECR_REPOSITORY:$ECR_REPOSITORY-$FULL_IMAGE
       docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

