name: Push to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPO: whist-exam-app
  IMAGE_NAME: app

jobs:
  push_to_ecr:
    name: Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push image to ECR
        id: build-and-push
        env:
          ECR_REPO_URI: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}
          IMAGE_TAG_LATEST: latest
          IMAGE_TAG_COMMIT_SHA: ${{ github.sha }}
          IMAGE_TAG_BRANCH: ${{ github.ref }}
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_LATEST }} -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG_BRANCH }}-${{ env.IMAGE_TAG_COMMIT_SHA }} .
          docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG_LATEST }} ${{ env.ECR_REPO_URI }}:${{ env.IMAGE_TAG_LATEST }}
          docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG_BRANCH }}-${{ env.IMAGE_TAG_COMMIT_SHA }} ${{ env.ECR_REPO_URI }}:${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG_BRANCH }}-${{ env.IMAGE_TAG_COMMIT_SHA }}
          docker push ${{ env.ECR_REPO_URI }}:${{ env.IMAGE_TAG_LATEST }}
          docker push ${{ env.ECR_REPO_URI }}:${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG_BRANCH }}-${{ env.IMAGE_TAG_COMMIT_SHA }}

